name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - killergotrekt
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version are you using?
      options:
        - 0.12.2
        - 0.12.1
        - 0.12
        - 0.10.11 and under
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Screenshots/Evidence
      description: Please copy and paste any relevant evidence
      render: shell

